* Gameboyz Theme
** Codename "mommod"
Heavily modified, based on Momentous Lite

Momentous Lite WordPress Theme

Copyright 2014 ThemeZee.com

Momentous Lite is distributed under the terms of the GNU GPL

* Schedule Outline
** Sprint 3: <2015-05-11 Mon> to <2015-05-24 Sun>
- Front Page
  - Navbar
    - on the backburner
- Comments
  - Plugin in place +login with external sites like facebook, twitter, steam, etc.+
  - Styling
- Ads
  - Front-end
    - placement
      - might have to call in the main loop with tiles
  - Back-end
    - Plugin
    - delivery

** Sprint 2: <2015-04-27 Mon> to <2015-05-10 Sun>
- Front Page
  - Newest Posts
    - On-going +Update: skeleton structure is mostly there, along with css rules+
    - Nah +Feature?: have layout change randomly+
  - mobile/touch screen
    - No +summary text won't work the same as it will on machine with a mouse+
    - No +need to come up with a way to display text without mouse hover+
  - Category Pages
    - Need to find the best way, wp has several ways this can be done
    - Note: in testing implimentation, the way newest posts and regular posts, if newest posts template runs out of posts, The Loop (wp term) restarts from the beginning once it gets to the regular post template, causing duplication on the displayed page
      - Shouldn't really be a problem in production, but it's a side note for the future
  - Navbar
    - Needs to be more fancy, layout is not optimal
- Posts
  - Done +Need to be able to set a page layout (review, news)+

** Sprint 1: <2015-04-13 Mon> to <2015-04-27 Mon>
1. +Purge features not need+ -> Features are still there in code, but out of the way
2. +Finish frontpage layout+ -> Continuing for sprint 2
3. +Templates+ -> Wp not obvious about post types, need to do more research
   1. News articles
   2. Review articles

* Requirements

The theme has been tested on all major browsers including Firefox, Opera, Chrome,  
Internet Explorer and Safari. Your browser should have JavaScript enabled to make this theme work!

The theme works on the latest Wordpress version without any problems. Previous versions have not been tested and are not supported. I suggest to update your wordpress installation, especially due to security flaws.

* Installation

Upload the theme files to your wordpress theme folder wp-content/themes and activate the theme in
your wordpress admin panel. That's it!

To find out more about installing WordPress themes please also see http://themezee.com/docs/install-wordpress-themes/


** Theme Options

*NOTE:* Would be nice to have the customizer work with our theme, but probably won't due to time constraints.

+Momentous Lite supports the awesome Theme Customizer for all theme settings.+
+Go to WP-Admin > Appearance > Customize to open the Customizer.+

* License

Gameboyz Theme, codename "mommod", is released under the GNU general public license GPLv2


Momentous Lite is released under the GNU general public license. 
That means you can use this theme on all of your websites - for personal or commercial purposes!

** Licenses of bundled resources

Genericons, Copyright 2014 Automattic, Inc.
The theme uses the Genericons icon font for postmeta, menu and social icons licensed under GNU GPL.

+ Source URL: http://genericons.com
+ License of Genericon Icon font: http://www.gnu.org/licenses/gpl.html


Default Fonts (Average Sans, Fjalla One)
Default Fonts used in the theme are from the Google Font API and are GPL-compatible licensed (SIL Open Font License (OFL))

+ https://www.google.com/fonts/specimen/Average+Sans
+ http://www.google.com/fonts/specimen/Fjalla+One
